python_tests(
    name="tests37",
    interpreter_constraints=[">=3.7.1,<3.8.0"],
    dependencies=["pkg:whl"]
)
python_tests(
    name="tests310",
    interpreter_constraints=[">=3.10.0,<3.11.0"],
    dependencies=["pkg:whl"]
)
