[GLOBAL]
pants_version = "2.15.0"
backend_packages = [
    "pants.backend.python"
]

[source]
root_patterns = ["/", "pkg/"]

[python]
enable_resolves = true

[anonymous-telemetry]
enabled = true
repo_id = "ED3CCABC-6067-47DD-A959-353BC3F02836"

[python.resolves]
37 = "3rdparty/python/37.lock"

[python.resolves_to_interpreter_constraints]
37 = [">=3.7.1,<3.8.0"]

[pytest]
lockfile = "3rdparty/python/pytest.lock"
